# Pre-commit hooks.
# python3 -m pip install pre-commit
# pre-commit install

repos:

  # Format Python
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
