name: Build
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      #- name: Build with Buildozer
      #  uses: ./master # REPLACE WITH ArtemSBulgakov/buildozer-action@v1
      #  id: buildozer
      #  with:
      #    repository_root: master
      #    workdir: .
      #    buildozer_version: stable
      - name: Build with Buildozer
        id: buildozer
        run: |
          pip3 install --user --upgrade buildozer Cython virtualenv
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          cd ${{ github.workspace }}
          buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: data
          ref: data # Branch name

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
          architecture: x64

      - name: Push binary to data branch
        if: github.event_name == 'push'
        run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
